RestaurantJISH-phase31/Models/order.cs
namespace RestaurantJISH_phase31.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int OrderId { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string PostalCode { get; set; }

        [Required]
        public string Phone { get; set; }

        [Column(TypeName = "date")]
        public DateTime OrderDate { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [StringLength(128)]
        public string userId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}

RestaurantJISH-phase31/Models/vieworder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestaurantJISH_phase31.Models
{
    public class vieworder
    {
        public order order { get; set; }
        public OrderItem OrderItem { get; set; }
    }
}

RestaurantJISH-phase31/Controllers/IndividualController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using RestaurantJISH_phase31.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantJISH_phase31.Models;
namespace RestaurantJISH_phase31.Controllers
{
    public class IndividualController : Controller
    {
        // GET: Individual
        [Authorize]
        public ActionResult checkout()
        {




            return View();
        }
        public ActionResult order(string RecieverName, string address, string phonenumber, string PostCode)
        {

            var userID = User.Identity.GetUserId();
            using (RestaurantContext db = new RestaurantContext())
            {
                order order = new order();
                order.userId = userID;
                order.Name = Request.QueryString["RecieverName"];
                order.Phone = Request.QueryString["phonenumber"];
                order.PostalCode = Request.QueryString["PostCode"];
                order.OrderDate = DateTime.Now;
                order.Address = Request.QueryString["address"];
                db.orders.Add(order);
                db.SaveChanges();
                int orderid = db.orders.Max(x => x.OrderId);
                foreach (Item item in (List<Item>)Session["Cart"])
                {
                    OrderItem neworderitem = new OrderItem();
                    neworderitem.OrderId = orderid;
                    neworderitem.FoodName = item.product.foodName;
                    neworderitem.RestaurantName = item.restaurant.Name;
                    neworderitem.Price = Convert.ToDouble(item.product.price);
                    neworderitem.quantity = Convert.ToInt32(item.quantity);
                    db.OrderItems.Add(neworderitem);
                    db.SaveChanges();
                }
                Session["cart"] = null;
                Session["quantity"] = null;
                ViewBag.orderinfo = "paid sucessfully!!!";

                return View("order");
            }
        }
        public ActionResult vieworders()
        {

            var userID = User.Identity.GetUserId();
            RestaurantContext db = new RestaurantContext();

            var model = from x in db.orders
                        join b in db.OrderItems on x.OrderId equals b.OrderId
                        where x.userId == userID
                        select new vieworder
                        {
                            order = x,
                            OrderItem = b
                        };


            return View(model);
        }
        public ActionResult detail(int? ordernumber)
        {
            var userID = User.Identity.GetUserId();
            RestaurantContext db = new RestaurantContext();

            var model = from x in db.orders
                        join b in db.OrderItems on x.OrderId equals b.OrderId
                        where x.userId == userID && b.OrderId == ordernumber
                        select new vieworder
                        {
                            order = x,
                            OrderItem = b
                        };

            ViewBag.orderId = ordernumber;
            return View(model);
        }
    }
}

RestaurantJISH-phase31/Views/Individual/checkout.cshtml
@using RestaurantJISH_phase31.Models
@{
    ViewBag.Title = "checkout";
}
<div class="row" style="margin-top:100px">
    <div class="col-md-offset-4 col-md-5">
        @if (Session["cart"] == null||Session["cart"].ToString() ==string.Empty)
        {
            <h3>Please add items, your cart is empty</h3>
        }
        else
        {
           
            <h3 style="color:brown">Please Enter Order Information: </h3>
                        using (Html.BeginForm("order", "Individual", FormMethod.Get, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <label for="RecieverName'">Reciever's Name: </label>
                    @Html.TextBox("RecieverName", null, new { @class = "form-control", placeholder = "name",type="name",required="required" })
                </div>
                <div class="form-group">
                    <label for="address">Address: </label>
                    @Html.TextBox("address", null, new { @class = "form-control", placeholder = "address", type = "address", required = "required" })
                </div>
                <div class="form-group">
                    <label for="phonenumber">Phone number: </label>
                    @Html.TextBox("phonenumber", null, new { @class = "form-control", placeholder = "phone number", pattern = "[0-9]{3}[0-9]{3}[0-9]{4}", required = "required" })
                </div>
                <div class="form-group">
                    <label for="PostCode">Post Code: </label>
                    @Html.TextBox("PostCode", null, new { @class = "form-control", placeholder = "post code", pattern= "[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ] ?[0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]", required = "required" })
                </div>
                <div class="jumbotron" style="padding:20px">
                    <h4 style="color:brown">Order detail</h4>
                    <table class="table table-condensed">
                        <tr>
                            <th>Option</th>

                            <th>FoodName</th>
                            <th>FoodPrice</th>
                            <th>FoodQuantity</th>
                            <th>total</th>
                        </tr>
                        @{
                            double s = 0;
        double op = 0;
                        }
                        @if (Session["Cart"] != null)
        {
            foreach (Item item in (List<Item>)Session["Cart"])
            {
                s = s + item.product.price * item.quantity;
                op = op + 1;
                                <tr>
                                    <td>@op</td>

                                    <td>@item.product.foodName</td>
                                    <td>$@item.product.price</td>
                                    <td>@item.quantity</td>
                                    <td>$@(item.product.price * item.quantity)</td>


                                </tr>

                            }
        }
                    </table>
                    <div class="row">
                        <div class="col-lg-offset-10" style="align:right">
                            Sub: $@s
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-offset-10" style="align:right">
                            @{

                                ViewBag.total = (s * 1.13);
                            }
                            Total:$@String.Format("{0:0.00}", ViewBag.total)
                        </div>
                    </div>
                    </div>
                    <button class="btn btn-primary" type="submit" id="payButton" value="Pay">Pay Now!</button>
                    }
                    }
                </div>
</div>

RestaurantJISH-phase31/Views/Individual/detail.cshtml
@{
    ViewBag.Title = "detail";
}
@model IEnumerable<RestaurantJISH_phase31.Models.vieworder>
<div style="margin-top:100px">

    <div class="row">
        <div class="col-md-offset-2 col-md-7">

            <h4>Order @ViewBag.orderId</h4>
            <table class="table table-hover">
                <tr>
                <tr>
                    <th>Option</th>
                    <th>Restaurant</th>
                    <th>FoodName</th>
                    <th>FoodPrice</th>
                    <th>FoodQuantity</th>
                    <th>total</th>
                </tr>
                @{
                    double s = 0;
                    double op = 0;
                }
             
                    @foreach (var item in Model)
                    {
                        s = s + Convert.ToDouble(item.OrderItem.Price) * Convert.ToDouble(item.OrderItem.quantity);
                        op = op + 1;
                        <tr>
                            <td>@op</td>
                            <td>@item.OrderItem.RestaurantName</td>
                            <td>@item.OrderItem.FoodName</td>
                            <td>$@item.OrderItem.Price</td>
                            <td>@item.OrderItem.quantity</td>
                            <td>$@(item.OrderItem.Price * item.OrderItem.quantity)</td>
                           

                        </tr>

                    }
                
                
                </table>
            <div class="row">
                <div class="col-lg-offset-10" style="align:right">
                    Sub: $@s
                </div>
            </div>
            <div class="row">
                <div class="col-lg-offset-10" style="align:right">
                    @{

                        ViewBag.total = (s * 1.13);
                    }
                    Total:$@String.Format("{0:0.00}", ViewBag.total)
                </div>
            </div>
            </div>
        </div>
    </div>

RestaurantJISH-phase31/Views/Individual/order.cshtml
@{
    ViewBag.Title = "order";
}
<div class="row">
    <div class="col-md-offset-4 col-md-5">
<h2 style="margin-top:100px">@ViewBag.orderinfo </h2>
        </div>
</div>

RestaurantJISH-phase31/Views/Individual/vieworders.cshtml
@{
    ViewBag.Title = "vieworders";
}
@model IEnumerable<RestaurantJISH_phase31.Models.vieworder>

<div style="margin-top:100px">

    <div class="row">
       <div  class="col-md-offset-2 col-md-7">
        <table class="table table-hover">
            <tr>
                <td>
                    OrderId
                </td>
                <td>
                    Name
                </td>
                <td>
                    Phone
                </td>
                <td>
                    PostCode
                </td>
                <td>
                    </td>
            </tr>
            @{
                int depulicated = 0;
            }
            @foreach (var item in Model)
            {
                if (item.order.OrderId != depulicated)
                {
                    <tr>
                        <td>@item.order.OrderId</td>
                        <td>@item.order.Name
                        </td>
                        <td>@item.order.Phone</td>
                        <td>@item.order.PostalCode</td>
                        <td>@Html.ActionLink("detail","detail","Individual",new {ordernumber = item.order.OrderId},null)</td>
                    </tr>
                    depulicated = item.order.OrderId;

                }


            }
        </table>
    </div>
</div>
    </div>
<div class="row">
    <div class="col-md-12">
        </div>
    </div>