RestaurantJISH-phase31/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using RestaurantJISH_phase31.Models;
using PagedList;
using PagedList.Mvc;
using System.Web.Mvc.Ajax;

namespace RestaurantJISH_phase31.Controllers
{
    public class RestaurantController : Controller
    {
        RestaurantContext db = new RestaurantContext();
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult List(string searchby)
        {

            if (searchby == null || searchby == string.Empty)
            {
                return View(db.Restaurants.ToList());
            }

            else
            {

                return View(db.Restaurants.Where(x => x.Name.Contains(searchby.ToLower()) || x.Type.Contains(searchby.ToLower()) || x.Area.Contains(searchby.ToLower()) || x.Description.Contains(searchby.ToLower()) || x.City.Contains(searchby.ToLower())).ToList());
            }
        }
        public ActionResult Menu(int id, int? page)
        {
            //create object of menulist
            menuDetailmodel mymodel = new menuDetailmodel();

            //add property of restaurant name to object
            string restaurantName = (db.Restaurants.Where(x => x.RestaurantId.Equals(id)).FirstOrDefault().Name);
            mymodel.restuarantName = restaurantName;
            //add property of 2 joined table list to object
            var list = db.Categories.Join(db.menus, c => c.CategoryId, m => m.CategoryId, (c, m) => new joinModel { category = c, menu = m }).Where(c => c.category.RestaurantId.Equals(id));
            mymodel.detailMenu = list.ToList().ToPagedList(page ?? 1, 12);
            //add category list to navbar property of this object
            var categoryList = db.Categories.Where(x => x.RestaurantId.Equals(id)).ToList();
            mymodel.navBarList = categoryList;
            Restaurant restaurantsInfo = db.Restaurants.Where(x => x.RestaurantId.Equals(id)).FirstOrDefault();
            mymodel.restuarantInformation = restaurantsInfo;
            //pass this object to the model    
            if (Request.IsAjaxRequest())
            {
                return PartialView("_PagedMenuList", mymodel);
            }
            else
            {
                return View(mymodel);
            }


        }


        public PartialViewResult detailOfeachCategory(int restaurantId, int categoryId, int? page)
        {
            //create object of menulist
            menuDetailmodel mymodel = new menuDetailmodel();

            //add property of restaurant name to object
            string restaurantName = (db.Restaurants.Where(x => x.RestaurantId.Equals(restaurantId)).FirstOrDefault().Name);
            mymodel.restuarantName = restaurantName;
            //add property of 2 joined table list to object
            var list = db.Categories.Join(db.menus, c => c.CategoryId, m => m.CategoryId, (c, m) => new joinModel { category = c, menu = m }).Where(c => c.category.RestaurantId.Equals(restaurantId) && c.category.CategoryId.Equals(categoryId));
            mymodel.detailMenu = list.ToList().ToPagedList(page ?? 1, 12);
            return PartialView("_productsForeachcategory", mymodel);
        }

    }
}

RestaurantJISH-phase31/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantJISH_phase31.Models;
namespace RestaurantJISH_phase31.Controllers
{
    public class ShoppingCartController : Controller
    {
        private RestaurantContext db = new RestaurantContext();
        // GET: ShoppingCart
        private int isExisting(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].product.foodId == id)
                    return i;
            return -1;
        }
        public ActionResult Cart()
        {
            return View("Cart");

        }
        int s = 0;
        public ActionResult orderNow(int id)
        {

            if (Session["Cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(db.menus.Find(id), 1));
                Session["Cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["Cart"];
                int index = isExisting(id);
                if (index == -1)
                {
                    cart.Add(new Item(db.menus.Find(id), 1));
                }
                else
                {
                    cart[index].quantity++;
                }
            }

            foreach (Item item in (List<Item>)Session["Cart"])
            {
                s = s + item.quantity;
                Session["quantity"] = s;
            }


            return PartialView("_cartnumber");
        }
        public ActionResult Delete(int id)
        {

            if (Session["Cart"] != null)
            {
                foreach (Item item in (List<Item>)Session["Cart"])
                {
                    s = s + item.quantity;
                }
                foreach (Item item in (List<Item>)Session["Cart"])
                {
                    if (item.product.foodId == id)
                    {
                        s = s - item.quantity;
                    }

                }
                Session["quantity"] = s;
                //return PartialView("_cartnumber");

                int index = isExisting(id);
                List<Item> cart = (List<Item>)Session["cart"];
                cart.RemoveAt(index);
                Session["cart"] = cart;

            }
            return View("cart");
        }

    }

}

RestaurantJISH-phase31/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.easing.1.3.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <script src="~/Scripts/menuAjax.js"></script>
    <script src="~/Scripts/addTocart.js"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" style="margin-bottom:0px">
        <div class="container-fluid" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                   <a href="~/Restaurant/Index"> <img src="~/assets/pageContent/jish-iloveimg-cropped.png" style="width:80px"/></a>
                
                </div>    
              @*@Html.ActionLink("EAT YO", "Index", "Restaurant",null,new { @class="navbar-header navbar-brand"})*@
              <a class="page-scroll navbar-brand" href="#contact"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
              
                </div>
            
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav navbar-right" style="padding-right:50px">
                          <li>@Html.Partial("_LoginPartial")</li>                   
                    </ul>
                  
                </div>
            </div>
    </div>
    
        @RenderBody()
      
        <footer  style="margin-top:50px" >
            <div id="contact" >
            <p style="text-align:center" >&copy;  2016 - By Jing Zhou</p>
   

            </div>
           
        </footer>
   

    @RenderSection("scripts", required: false)
</body>
</html>

RestaurantJISH-phase31/Views/Shared/_cartnumber.cshtml
@Session["quantity"]

RestaurantJISH-phase31/Views/Shared/_productsForeachcategory.cshtml
@using RestaurantJISH_phase31.Models
@model menuDetailmodel




<div  style="padding-left:50px"class="col-sm-7">

    <div class="row carousel-holder">

        <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                <div class="carousel-inner">

                    @for (int i = 0; i < Model.detailMenu.Count(); i++)
                    {
                        if (i == Model.detailMenu.Count() - 1)
                        {
                            <div class="item active">
                                <img class="slide-image" style="width:1050px;"src="~/assets/@Model.detailMenu[i].category.RestaurantId/@Model.detailMenu[i].menu.foodImage" alt="">
                            </div>
                        }
                        else
                        {
                            <div class="item">
                                <img class="slide-image" style="width:1050px;"src="~/assets/@Model.detailMenu[i].category.RestaurantId/@Model.detailMenu[i].menu.foodImage" alt="">
                            </div>
                        }
                    }

                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

    </div>



    <div class="row">
    @foreach (var item in Model.detailMenu)
    {
        <div class="products">
            <div class="product">
                <div class="col-sm-4 col-lg-4 col-md-4" style="margin-top:20px">
                    <div class="thumbnail" style="height:260px">
                        <div class="hovereffect" style="height:120px;margin-bottom:20px">
                            <img class="picture-hover" src="~/assets/@item.category.RestaurantId/@item.menu.foodImage" alt="food picture" style="width:320px;height:120px">
                            <div class="overlay">
                                <a class="info" data-toggle="modal" id="open-ModalDialog"
                                   data-foodname="@item.menu.foodName.ToUpper()" data-foodimage="@item.menu.foodImage"
                                   data-foodprice="@item.menu.price" data-resturantsid="@item.category.RestaurantId"
                                   data-description="@item.menu.briefDescription.First().ToString().ToUpper()@item.menu.briefDescription.Substring(1)"
                                   data-target="#myModal"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
                            </div>
                        </div>

                        <div class="caption">
                            <h4 class="pull-right" style="margin-top:0px">$@item.menu.price</h4>
                            <h4>
                                <span style="font-size:large;color:darkslateblue">@item.menu.foodName.ToUpper()</span>
                            </h4>
                            <p>@item.menu.briefDescription.First().ToString().ToUpper()@item.menu.briefDescription.Substring(1)</p>

                        </div>
                        @Ajax.ActionLink("Buy", "orderNow", "ShoppingCart", new { id = item.menu.foodId }, new AjaxOptions { HttpMethod = "get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "cart-number" }, new { @class = "add-to-cart btn btn-primary", style = "bottom:30px;right:20px;position:absolute" })
                    </div>
                </div>
                </div>
            </div>
                }

            </div>

        </div>
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content" style="background-color:rgba(0, 0, 0,0.4)">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" style="color:white;text-align:center"></h4>

                    </div>
                    <div class="modal-body" style="color:white;text-align:center">
                        <div class="row">
                            <img id="imageArea" src="~/assets/1001/1.jpg" style="width:100%;height:100%" />
                        </div>
                        <div class="row">
                            <h4 id="priceArea">Price: </h4>
                            <h4 id="descriptionArea">Description: </h4>
                        </div>

                    </div>
                    <div class="modal-footer" style="color:white;text-align:center">

                        &copy;2016 - By Jing Zhou
                    </div>
                </div>
            </div>
        </div>